version: '3.8'

services:
    db:
        container_name: fs-beego-db
        image: postgres:14.1-alpine
        ports:
            - 5432:5432
        environment:
            TZ: "UTC"
            LANG: ja_JP.UTF-8
            POSTGRES_DB: fs-beego
            POSTGRES_USER: fs-beego
            POSTGRES_PASSWORD: fs-beego
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
            POSTGRES_HOST_AUTH_METHOD: trust
